title: blog
description: My personal blog about video games, movies, television, and whatever else I find worth writing about.
url: "https://johnnguyenn77.github.io"
baseurl: ""
permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
